<?php
// filepath: c:\xampp\htdocs\pet-shelter\lang\sr.php
return [
    // General
    'pet_shelter_management_system' => 'Sistem upravljanja prihvatilišta za kućne ljubimce',
    'pet_shelter' => 'Prihvatilište za ljubimce',
    'pet_details' => 'Detalji ljubimca',
    'back_to_all_pets' => 'Nazad na sve ljubimce',
    'edit' => 'Izmeni',
    'save' => 'Sačuvaj',
    'cancel' => 'Otkaži',
    'close' => 'Zatvori',
    'unknown' => 'Nepoznato',
    'not_available' => 'Nije dostupno',
    'no_image_available' => 'Nema slike',
    'dashboard' => 'Kontrolna tabla',
    'pets' => 'Ljubimci',
    'users' => 'Korisnici',
    'profile' => 'Profil',
    'logout' => 'Odjava',
    'welcome' => 'Dobrodošli',
    'recent_activity' => 'Nedavne aktivnosti',
    'title' => 'Naslov',
    'created_by' => 'Kreirao',
    'created_at' => 'Datum kreiranja',
    'actions' => 'Akcije',
    'add_pet' => 'Dodaj ljubimca',
    'view_pets' => 'Pregledaj ljubimce',
    'register_user' => 'Registruj korisnika',
    'select_species' => 'Izaberite vrstu',
    'microchip_information' => 'Informacije o mikročipu',
    
    // Pet info
    'status' => 'Status',
    'pet_status' => 'Status ljubimca',
    'presence_in_shelter' => 'Prisustvo u prihvatilištu',
    'incoming_date' => 'Datum dolaska',
    'species' => 'Vrsta',
    'dog' => 'Pas',
    'cat' => 'Mačka',
    'rabbit' => 'Zec',
    'bird' => 'Ptica',
    'breed' => 'Rasa',
    'sex' => 'Pol',
    'date_of_birth' => 'Datum rođenja',
    'coat_color' => 'Boja dlake',
    'coat_type' => 'Tip dlake',
    'male' => 'Mužjak',
    'female' => 'Ženka',
    'available' => 'Dostupan',
    'adopted' => 'Usvojen',
    'fostered' => 'Na privremenom čuvanju',
    'medical' => 'Medicinski slučaj',
    'yes' => 'Da',
    'no' => 'Ne',
    'available_for_adoption' => 'Dostupan za usvajanje',
    'under_medical_care' => 'Pod medicinskom negom',

    // Identification
    'identification' => 'Identifikacija',
    'microchip_number' => 'Broj mikročipa',
    'microchip_date' => 'Datum mikročipiranja',
    'microchip_location' => 'Lokacija mikročipa',

    // Vaccinations
    'vaccinations' => 'Vakcinacije',
    'add_vaccination' => 'Dodaj vakcinaciju',
    'edit_vaccination' => 'Izmeni vakcinaciju',
    'vaccine_type' => 'Tip vakcine',
    'select_vaccine_type' => 'Izaberite tip vakcine',
    'vaccine_name' => 'Naziv vakcine',
    'batch_number' => 'Broj serije',
    'vaccination_date' => 'Datum vakcinacije',
    'expiry_date' => 'Datum isteka',
    'veterinarian' => 'Veterinar',
    'no_vaccination_records' => 'Nema podataka o vakcinaciji.',
    'save_vaccination' => 'Sačuvaj vakcinaciju',
    'save_changes' => 'Sačuvaj izmene',
    'add_vaccination_record' => 'Dodaj zapis o vakcinaciji',
    'edit_vaccination_records' => 'Izmeni zapise o vakcinaciji',

    // Vaccine types
    'rabies' => 'Besnilo',
    'distemper' => 'Štenećak',
    'parvovirus' => 'Parvovirus',
    'other' => 'Ostalo',

    // Health Checks
    'health_checks' => 'Zdravstveni pregledi',
    'add_health_check' => 'Dodaj zdravstveni pregled',
    'edit_health_check' => 'Izmeni zdravstveni pregled',
    'no_health_check_records' => 'Nema podataka o zdravstvenim pregledima.',
    'check_date' => 'Datum pregleda',
    'health_status' => 'Zdravstveno stanje',
    'diagnosis' => 'Dijagnoza',
    'treatment_plan' => 'Plan lečenja',
    'clinical_exam' => 'Klinički pregled',
    'information_on_clinical_examinations' => 'Informacije o kliničkim pregledima',
    'animal_statement' => 'Opis životinje',
    'health_notes' => 'Zdravstvene napomene',
    'additional_notes' => 'Dodatne napomene',
    'condition' => 'Stanje',
    'health_status' => 'Zdravstveno stanje',
    'select_health_status' => 'Izaberite zdravstveno stanje',

    // Health status options
    'excellent' => 'Odlično',
    'good' => 'Dobro',
    'not_good' => 'Nije dobro',
    'fair' => 'Zadovoljavajuće',
    'poor' => 'Loše',
    'critical' => 'Kritično',

    // Alerts & messages
    'health_check_added' => 'Zdravstveni pregled je uspešno dodat!',
    'vaccination_added' => 'Vakcinacija je uspešno dodata!',
    'health_check_updated' => 'Zdravstveni pregledi su uspešno izmenjeni!',
    'vaccination_updated' => 'Vakcinacije su uspešno izmenjene!',
    'pet_updated' => 'Podaci o ljubimcu su uspešno izmenjeni!',

    // Table headers
    'type' => 'Tip',
    'name' => 'Ime',
    'date' => 'Datum',
    'expiry' => 'Ističe',
    'actions' => 'Akcije',

    // Modal titles
    'add_health_check_title' => 'Dodaj zdravstveni pregled',
    'edit_health_check_title' => 'Izmeni zdravstveni pregled',
    'add_vaccination_title' => 'Dodaj zapis o vakcinaciji',
    'edit_vaccination_title' => 'Izmeni zapise o vakcinaciji',

    
    'show' => 'Prikaži',
    'rows' => 'redova',
    'all_pets' => 'Svi ljubimci',
    'search_pets' => 'Pretraga ljubimaca...',
    'search' => 'Pretraži',
    'add_new_pet' => 'Dodaj ljubimca',
    'image' => 'Slika',
    'view' => 'Pregled',
    'previous' => 'Prethodna',
    'next' => 'Sledeća',
    'basic_information' => 'Osnovne informacije',
];